version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5
        environment:
          MIX_ENV: test

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-build-cache-{{ .Branch }}-{{ checksum "mix.lock" }}

      - run: mix deps.get
      
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
          
      - run: mix test
      
      - save_cache:
          key: v1-build-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "_build"
      - store_test_results:
          path: _build/test/lib/proxer_ex/